version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
            # - /var/www/resources/view
            - ./.docker/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - 9000:8080
        depends_on:
            - database
            - redis
    database:
        container_name: database
        image: mariadb:10
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=db_hris
            - MYSQL_USER=hris
            - MYSQL_PASSWORD=BenguetLGU123!
            - MYSQL_ROOT_PASSWORD=biptis123456!
        volumes:
            - db-data:/var/lib/mysql
    redis:
        container_name:  redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6380:6379
volumes:
    db-data: ~
